import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <script src="//customfingerprints.bablosoft.com/clientsafe.js"></script>
        <script>
          {`
            document.addEventListener("DOMContentLoaded", function() {
              if (typeof ProcessFingerprint === "function") {
                ProcessFingerprint(false, "t4ck3cjtdi6k9spt4mgu654rxkcuhjm1ya40blt292ffr7getn5nwcr6x8u85r8s");
              } else {
                console.error("ProcessFingerprint is not defined. Ensure clientsafe.js is loaded.");
              }
            });
          `}
        </script>
      </body>
    </html>
  );
}
